version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Goh_Hern_Yee_ACCAD4_Assignment
hooks:
  ApplicationStop: #hooks to tell code deploy
    - location: scripts/stop-server.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: root